language: java
jdk: oraclejdk8

services:
  - docker

sudo: required

script:
  - mvn clean verify
  - mvn docker:build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push kune/phoenix;
